// 2025 NCAA Tournament Teams by Region (64 teams)
const REGIONS = ['South', 'East', 'West', 'Midwest'];

const TOURNAMENT_TEAMS = {
  South: [
    { seed: 1, name: 'Auburn' },
    { seed: 16, name: 'Alabama St/Saint Francis' },
    { seed: 8, name: 'Louisville' },
    { seed: 9, name: 'Creighton' },
    { seed: 5, name: 'Michigan' },
    { seed: 12, name: 'UC San Diego' },
    { seed: 4, name: 'Texas A&M' },
    { seed: 13, name: 'Yale' },
    { seed: 6, name: 'Ole Miss' },
    { seed: 11, name: 'San Diego St' },
    { seed: 3, name: 'Iowa St' },
    { seed: 14, name: 'Lipscomb' },
    { seed: 7, name: 'Marquette' },
    { seed: 10, name: 'New Mexico' },
    { seed: 2, name: 'Michigan St' },
    { seed: 15, name: 'Bryant' },
  ],
  West: [
    { seed: 1, name: 'Florida' },
    { seed: 16, name: 'Norfolk St' },
    { seed: 8, name: 'UConn' },
    { seed: 9, name: 'Oklahoma' },
    { seed: 5, name: 'Memphis' },
    { seed: 12, name: 'Colorado St' },
    { seed: 4, name: 'Maryland' },
    { seed: 13, name: 'Grand Canyon' },
    { seed: 6, name: 'Missouri' },
    { seed: 11, name: 'Drake' },
    { seed: 3, name: 'Texas Tech' },
    { seed: 14, name: 'UNC Wilmington' },
    { seed: 7, name: 'Kansas' },
    { seed: 10, name: 'Arkansas' },
    { seed: 2, name: 'St. John\'s' },
    { seed: 15, name: 'Omaha' },
  ],
  East: [
    { seed: 1, name: 'Duke' },
    { seed: 16, name: 'American/Mt St Mary\'s' },
    { seed: 8, name: 'Mississippi St' },
    { seed: 9, name: 'Baylor' },
    { seed: 5, name: 'Oregon' },
    { seed: 12, name: 'Liberty' },
    { seed: 4, name: 'Arizona' },
    { seed: 13, name: 'Akron' },
    { seed: 6, name: 'BYU' },
    { seed: 11, name: 'VCU' },
    { seed: 3, name: 'Wisconsin' },
    { seed: 14, name: 'Montana' },
    { seed: 7, name: 'Saint Mary\'s' },
    { seed: 10, name: 'Vanderbilt' },
    { seed: 2, name: 'Alabama' },
    { seed: 15, name: 'Robert Morris' },
  ],
  Midwest: [
    { seed: 1, name: 'Houston' },
    { seed: 16, name: 'SIU Edwardsville' },
    { seed: 8, name: 'Gonzaga' },
    { seed: 9, name: 'Georgia' },
    { seed: 5, name: 'Clemson' },
    { seed: 12, name: 'McNeese' },
    { seed: 4, name: 'Purdue' },
    { seed: 13, name: 'High Point' },
    { seed: 6, name: 'Illinois' },
    { seed: 11, name: 'Texas/Xavier' },
    { seed: 3, name: 'Kentucky' },
    { seed: 14, name: 'Troy' },
    { seed: 7, name: 'UCLA' },
    { seed: 10, name: 'Utah St' },
    { seed: 2, name: 'Tennessee' },
    { seed: 15, name: 'Wofford' },
  ],
};

// Round names and scoring
const ROUNDS = [
  { name: 'Round of 64', shortName: 'R64', points: 10 },
  { name: 'Round of 32', shortName: 'R32', points: 20 },
  { name: 'Sweet 16', shortName: 'S16', points: 40 },
  { name: 'Elite 8', shortName: 'E8', points: 80 },
  { name: 'Final Four', shortName: 'F4', points: 160 },
  { name: 'Championship', shortName: 'CHAMP', points: 320 },
];
